TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += transtechnik.proto

DB += transtechnik.db

#=======================================
include $(TOP)/configure/RULES
