TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += transtechnik.proto

DB += transtechnik.db
DB += transtechnik_status_bit.db

#=======================================
include $(TOP)/configure/RULES
